/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-24 03:09:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1582162448499L));
    _jspx_dependants.put("jar:file:/C:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" type=\"text/css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\n");
      out.write("\t\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<title>header</title>\n");
      out.write("<style>\n");
      out.write(".profileBox{\n");
      out.write("  width: 100%;\n");
      out.write("  height: 160px; \n");
      out.write("  border-radius: 70%;\n");
      out.write("  overflow: hidden;\n");
      out.write("}\n");
      out.write(".profileImage{\n");
      out.write("width: 100%;\n");
      out.write("height: 100%;\n");
      out.write("object-fit: cover;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body class=\"nanum\">\n");
      out.write("\t\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<nav\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark bg-primary fixed-top headerOpacity\">\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/square\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/emoji.png\" style=\"width: 25px\"/></a>\n");
      out.write("\t\t\t<input class=\"form-control mr-sm-2\" type=\"text\"\n");
      out.write("\t\t\t\tplaceholder=\"검색할 골목 키워드\" id=\"searchStreet\" name=\"searchStreet\"\n");
      out.write("\t\t\t\tstyle=\"width: 300px\">\n");
      out.write("\t\t\t<button class=\"btn btn-secondary my-2 my-sm-0\" type=\"button\"\n");
      out.write("\t\t\t \t\tonclick=\"searchValidate()\">Search</button>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\tfunction searchValidate() {\n");
      out.write("\t\t\t\t/* alert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.districtNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\")\n");
      out.write("\t\t\t\talert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.streetSort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") */\n");
      out.write("\t\t\t\tvar regExp = /^[\\w가-힣]{2,}$/;\n");
      out.write("\t\t\t\tvar searchStreet = $(\"#searchStreet\").val();\n");
      out.write("\t\t\t\tconsole.log(searchStreet);\n");
      out.write("\t\t\t\tif (!regExp.test(searchStreet)){\n");
      out.write("\t\t\t\t\talert(\"2글자 이상의 완성된 글자를 입력해주세요.\");\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tlocation.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchStreet=\" + searchStreet;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\">\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto\">\n");
      out.write("\t\t\t</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"dropdown\">\n");
      out.write("\t\t\t\t<div class=\"dropdown-toggle headerImg\" type=\"button\"\n");
      out.write("\t\t\t\t\tid=\"alarmButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/alarm2.png\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\n");
      out.write("\t\t\t\t\taria-labelledby=\"alarmButton\" id=\"alarmDrop\">\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" data-toggle=\"modal\">'조미현'님이 친구요청을 수락하셨습니다.</a> \n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" data-toggle=\"modal\">'20대 인싸들' 골목에서 추방당하셨습니다.</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- ------------------------------태훈 추가-------------------------------->\n");
      out.write("\t\t\t<script>\n");
      out.write("\t\t\t\t$(\"#alarmButton\").on(\"click\", function(){\n");
      out.write("\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/square/selectAlarm\",\n");
      out.write("\t\t\t\t\t\tdataType : \"json\",\n");
      out.write("\t\t\t\t\t\tsuccess : function(alList) {\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"ajax 통신 성공\")\n");
      out.write("\t\t\t\t\t\t\tconsole.log(alList);\n");
      out.write("\t\t\t\t\t\t\t$(\"#alarmDrop\").html(\"\");\n");
      out.write("\t\t\t\t\t\t\tif(alList == \"\"){\n");
      out.write("\t\t\t\t\t\t\t\tvar $alarm = $(\"<a>\").prop(\"class\", \"dropdown-item nanum\").text(\"조회된 알람이 없습니다.\")\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#alarmDrop\").append($alarm);\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\t$.each(alList, function(index, item){\n");
      out.write("\t\t\t\t\t\t\t\t\t//console.log(alList[index])\n");
      out.write("\t\t\t\t\t\t\t\t\tvar $alarm = $(\"<a>\").prop(\"class\", \"dropdown-item nanum\").text(item.eventer + \", \" + item.alarmContent);\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#alarmDrop\").append($alarm);\n");
      out.write("\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\terror : function() {\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\")\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t\t})\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t<div class=\"dropdown\">\n");
      out.write("\t\t\t\t<div class=\"dropdown-toggle headerImg\" type=\"button\"\n");
      out.write("\t\t\t\t\tid=\"mypageButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/profileImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberProfileUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\n");
      out.write("\t\t\t\t\taria-labelledby=\"mypageButton\">\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" data-toggle=\"modal\" data-target=\"#profileModal\" id=\"abcde\">내정보 조회</a> \n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" data-toggle=\"modal\" data-target=\"#golmokModal\" id=\"hoho\">내골목 조회</a>\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" data-toggle=\"modal\">1:1 문의</a> \n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" data-toggle=\"modal\">공지사항</a>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item nanum\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout\">로그아웃</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<!-- profile Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"profileModal\" data-backdrop=\"static\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"profileModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\" style=\"width:496px;\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("            <h2 class=\"modal-title nanum\" id=\"profileModalLabel\" style=\"font-weight: bold;\">내정보 조회</h2>\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          \t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("        \t</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("            <!-- content start -->\n");
      out.write("                <!-- profile image start -->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                <div class=\"col-md-4\"></div>\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"profileBox\">\n");
      out.write("                    <img class=\"profileImage\" src=\"\" alt=\"이미지\" id=\"memberProfileUrl\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4\"></div>\n");
      out.write("                </div>\n");
      out.write("                <!-- profile image end-->\n");
      out.write("                <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3\"></div>\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <input type=\"text\" id=\"memberNickName\" class=\"nanum form-control-plaintext text-center\" style=\"font-size: 35px;font-weight: bold;\" readonly>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                <div class=\"col-md-2\"></div>\n");
      out.write("                <div class=\"col-md-8\"><input type=\"text\" id=\"memberEmail\" class=\"nanum form-control-plaintext text-center\" style=\"font-size: 25px;font-weight: bold;\" readonly></div>\n");
      out.write("                <div class=\"col-md-2\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                <label class=\"col-sm-2 col-form-label text-center nanum\" style=\"font-weight: bold; font-size: 16px;\">이름</label>\n");
      out.write("                <div class=\"col-sm-4\">\n");
      out.write("                    <input type=\"text\" readonly id=\"memberName\" class=\"nanum form-control-plaintext text-center\"  style=\"font-size: 25px;\">\n");
      out.write("                </div>\n");
      out.write("                <label class=\"col-sm-2 col-form-label text-center nanum\" style=\"font-weight: bold; font-size: 16px;\">나이</label>\n");
      out.write("                <div class=\"col-sm-4\">\n");
      out.write("                    <input type=\"text\" readonly id=\"memberAge\" class=\"nanum form-control-plaintext text-center\" style=\"font-size: 25px;\">\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                <label class=\"col-sm-2 col-form-label text-center nanum\" style=\"font-weight: bold; font-size: 16px;\">성별</label>\n");
      out.write("                <div class=\"col-sm-4\">\n");
      out.write("                \t<input type=\"text\" readonly id=\"memberGender\" class=\"nanum form-control-plaintext text-center\" style=\"font-size: 25px;\">\n");
      out.write("                </div>\n");
      out.write("                <label class=\"col-sm-2 col-form-label text-center nanum\" style=\"font-weight: bold; font-size: 16px;\">전화번호</label>\n");
      out.write("                <div class=\"col-sm-4\">\n");
      out.write("                    <input type=\"text\" readonly id=\"memberPhone\" class=\"nanum form-control-plaintext text-center\" style=\"font-size: 22px;\">\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\" id=\"memberProfileHobby\">\n");
      out.write("              \t<!-- 관심사 영역 -->\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("                <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <a class=\"btn btn-primary btn-lg btn-block nanum\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/MoveupdateForm?memberNo=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" role=\"button\" style=\"font-weight: bold;\">내정보 수정</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <a class=\"btn btn-primary btn-lg btn-block nanum\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/deleteForm\" role=\"button\" style=\"font-weight: bold;\">회원 탈퇴</a>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- content end -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- end -->\n");
      out.write("        \n");
      out.write("        <!-- golmok Modal -->\n");
      out.write("        <div class=\"modal fade\" id=\"golmokModal\" data-backdrop=\"static\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"golmokModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-lg\" role=\"document\" style=\"width:800px;\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                <h2 class=\"modal-title nanum\" id=\"golmokModalLabel\" style=\"font-weight: bold;\">내골목 조회</h2>\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t          \t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t        \t</button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                <!-- content start -->\n");
      out.write("\t                <div class=\"container-fluid\" id=\"myStreetInfomation\">\n");
      out.write("\t\t\t\t\t\t<!-- 내골목 정보 구역 -->\n");
      out.write("\t                </div>\n");
      out.write("                <!-- content end -->\n");
      out.write("                 </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- end -->\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("\t\t/* 내정보 조회용 회원정보,회원관심사 DB조회용 ajax */\n");
      out.write("       \t$(\"#abcde\").on(\"click\",function(){\n");
      out.write("       \t\t$.ajax({\n");
      out.write("       \t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/selectProfileMember\",\n");
      out.write("       \t\t\tdata : {memberEmail : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" , memberNo : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" },\n");
      out.write("       \t\t\ttype : \"post\",\n");
      out.write("       \t\t\tdataType : \"json\",\n");
      out.write("       \t\t\tsuccess : function(mList){\n");
      out.write("       \t\t\t\t\n");
      out.write("       \t\t\t\t// 회원정보\n");
      out.write("       \t\t\t\t$(\"#memberProfileUrl\").prop(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/profileImage/\"+mList[0].memberProfileUrl);\n");
      out.write("       \t\t\t\t$(\"#memberNickName\").val(mList[0].memberNickname);\n");
      out.write("       \t\t\t\t$(\"#memberEmail\").val(mList[0].memberEmail);\n");
      out.write("       \t\t\t\t$(\"#memberName\").val(mList[0].memberNm);\n");
      out.write("       \t\t\t\t$(\"#memberAge\").val(mList[0].memberAge);\n");
      out.write("       \t\t\t\t$(\"#memberPhone\").val(mList[0].memberPhone);\n");
      out.write("       \t\t\t\tif(mList[0].memberGender == \"M\") {\n");
      out.write("       \t\t\t\t\t$(\"#memberGender\").val(\"남성\");\t\n");
      out.write("       \t\t\t\t}else {\n");
      out.write("       \t\t\t\t\t$(\"#memberGender\").val(\"여성\");\n");
      out.write("       \t\t\t\t}\n");
      out.write("       \t\t\t\t// 회원정보 끝\n");
      out.write("       \t\t\t\t\n");
      out.write("            \t\t// 회원 관심사\n");
      out.write("       \t\t\t\tvar $divPlus = $(\"#memberProfileHobby\");\n");
      out.write("            \t\t\n");
      out.write("       \t\t\t\tfor(var i=1;i<Object.keys(mList).length;i++){\n");
      out.write("       \t\t\t\t\tif(i == 1) { // 제일 처음 관심사\n");
      out.write("       \t\t\t\t\t\tvar $divPlus1 = $(\"<div class='col-sm-10'>\");\n");
      out.write("       \t       \t\t\t\tvar $labelPlus = $(\"<label>\");\n");
      out.write("       \t       \t\t\t\tvar $inputPlus = $(\"<input>\");\n");
      out.write("       \t\t\t\t\t\t$labelPlus.addClass(\"col-sm-2 col-form-label text-center nanum\").css({\"font-weight\" : \"bold\",\"font-size\": \"16px\"}).html(\"관심분야\");\n");
      out.write("       \t\t\t\t\t\t$inputPlus.prop({\"type\":\"text\",\"readonly\":\"true\"}).css({\"color\" : \"blue\",\"font-size\": \"25px\"})\n");
      out.write("       \t\t\t\t\t\t\t\t  .addClass(\"nanum form-control-plaintext\").val(\"#\" + mList[1].hobbyName);\n");
      out.write("       \t\t\t\t\t\t$divPlus1.append($inputPlus);\n");
      out.write("       \t\t\t\t\t\tif(document.getElementById(\"memberProfileHobby\").childElementCount < (Object.keys(mList).length-1)*2) {\n");
      out.write("       \t\t\t\t\t\t\t$divPlus.append($labelPlus);\n");
      out.write("           \t\t\t\t\t\t$divPlus.append($divPlus1);\t\n");
      out.write("       \t\t\t\t\t\t}\n");
      out.write("       \t\t\t\t\t} else { // 그 다음 관심사\n");
      out.write("       \t\t\t\t\t\tvar $divPlus1 = $(\"<div class='col-sm-10'>\");\n");
      out.write("       \t       \t\t\t\tvar $labelPlus = $(\"<label>\");\n");
      out.write("       \t       \t\t\t\tvar $inputPlus = $(\"<input>\");\n");
      out.write("       \t\t\t\t\t\t$labelPlus.addClass(\"col-sm-2 col-form-label text-center nanum\").css({\"font-weight\" : \"bold\",\"font-size\": \"16px\"});\n");
      out.write("       \t\t\t\t\t\t$inputPlus.prop({\"type\":\"text\",\"readonly\":\"true\"}).css({\"color\" : \"blue\",\"font-size\": \"25px\"})\n");
      out.write("       \t\t\t\t\t\t\t\t  .addClass(\"nanum form-control-plaintext\").val(\"#\" + mList[i].hobbyName);\n");
      out.write("       \t\t\t\t\t\t$divPlus1.append($inputPlus);\n");
      out.write("       \t\t\t\t\t\tif(document.getElementById(\"memberProfileHobby\").childElementCount < (Object.keys(mList).length-1)*2) {\n");
      out.write("       \t\t\t\t\t\t\t$divPlus.append($labelPlus);\n");
      out.write("           \t\t\t\t\t\t$divPlus.append($divPlus1);\t\n");
      out.write("       \t\t\t\t\t\t}\n");
      out.write("       \t\t\t\t\t}\n");
      out.write("       \t\t\t\t}\n");
      out.write("       \t\t\t\t// 회원 관심사 끝\n");
      out.write("       \t\t\t\t\n");
      out.write("       \t\t\t},\n");
      out.write("       \t\t\terror : function(e){\n");
      out.write("           \t\t\tconsole.log(\"ajax 통신 실패\");\n");
      out.write("           \t\t\tconsole.log(e);\n");
      out.write("           \t\t}\n");
      out.write("       \t\t\t\n");
      out.write("       \t\t});\n");
      out.write("       \t\t\n");
      out.write("       \t});\n");
      out.write("\t\t\n");
      out.write("       \t// 내골목 조회용 골목정보,골목 키워드 DB조회용 ajax \n");
      out.write("       \t$(\"#hoho\").on(\"click\",function(){\n");
      out.write("       \t\t$.ajax({\n");
      out.write("       \t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/selectMyStreet\",\n");
      out.write("       \t\t\tdata : {memberNo : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("},\n");
      out.write("       \t\t\ttype : \"post\",\n");
      out.write("       \t\t\tdataType : \"json\",\n");
      out.write("       \t\t\tsuccess : function(streetInfo){\n");
      out.write("       \t\t\t\t\n");
      out.write("       \t\t\t\tif(Object.keys(streetInfo).length == 0) {\n");
      out.write("       \t\t\t\t\tif(document.getElementById(\"myStreetInfomation\").childElementCount < 1) {\n");
      out.write("       \t\t\t\t\t\t$hPlus = $(\"<h4 class='nanum'>\").html(\"가입한 골목이 없습니다.\");\n");
      out.write("           \t\t\t\t\t$(\"#myStreetInfomation\").append($hPlus);\t\n");
      out.write("       \t\t\t\t\t}\n");
      out.write("       \t\t\t\t} else {\n");
      out.write("       \t\t\t\t\t// 내 골목 수 만큼 반복\n");
      out.write("           \t\t\t\tfor(var i=0;i<Object.keys(streetInfo.myStreet).length;i++){ \n");
      out.write("           \t\t\t\t\tvar streetNo = ((streetInfo.myStreet)[i]).streetNo;\n");
      out.write("           \t\t\t\t\tvar $divPlus = $(\"<div class='row'>\");\n");
      out.write("           \t\t\t\t\tvar $divPlus1 = $(\"<div>\").addClass(\"col-md-4\").css({\"position\":\"relative\",\"height\":\"364px\"});\n");
      out.write("           \t\t\t\t\tvar $divPlus2 = $(\"<div class='col-md-1'>\");\n");
      out.write("           \t\t\t\t\tvar $divPlus3 = $(\"<div class='col-md-7'>\");\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\tvar $divPlus4 = $(\"<div class='col-md-9'>\");\n");
      out.write("           \t\t\t\t\tvar $divPlus5 = $(\"<div class='col-md-3'>\");\n");
      out.write("           \t\t\t\t\tvar $divPlus6 = $(\"<div class='col-md-12'>\");\n");
      out.write("           \t\t\t\t\tvar $imgPlus = $(\"<img>\").prop({\"src\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/골목2.jpg\", \"alt\":\"이미지\"})\n");
      out.write("           \t\t\t\t\t\t\t\t\t.css({\"position\":\"absolute\",\"z-index\":\"10\",\"width\":\"100%\",\"height\":\"100%\"});\n");
      out.write("           \t\t\t\t\tvar $spanPlus = $(\"<span class='badge badge-pill badge-info'>\").css({\"position\":\"absolute\", \"z-index\":\"100\", \"font-size\":\"15px\"})\n");
      out.write("           \t\t\t\t\t\t\t\t\t.html(\"개설 골목\");\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 1\n");
      out.write("           \t\t\t\t\t$divPlus1.append($imgPlus);\n");
      out.write("           \t\t\t\t\tif( ((streetInfo.myStreet)[i]).citizenGrade == 'M'.charAt(0) ) {\n");
      out.write("           \t\t\t\t\t\t// 개설한 골목일 경우\n");
      out.write("           \t\t\t\t\t\t$divPlus1.append($spanPlus);\n");
      out.write("           \t\t\t\t\t}\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 2\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 3_1\n");
      out.write("           \t\t\t\t\tvar $divPlus31 = $(\"<div class='row'>\"); \n");
      out.write("\t\t\t\t\t\t\tvar $sector1 = $(\"<div class='col-md-9'>\");\n");
      out.write("\t\t\t\t\t\t\tvar $sector2 = $(\"<div class='col-md-3'>\");\n");
      out.write("           \t\t\t\t\tvar $sname = $(\"<input class='form-control-plaintext nanum'>\").prop({\"type\":\"text\",\"readonly\":true})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.css({\"font-weight\":\"bold\",\"font-size\":\"25px\"}).val(((streetInfo.myStreet)[i]).streetNm);\n");
      out.write("           \t\t\t\t\t$sector1.append($sname);\n");
      out.write("           \t\t\t\t\tvar $sdistrict = $(\"<button class='btn btn-outline-success text-center'>\").css({\"font-weight\":\"bold\",\"font-size\":\"13px\"})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.prop({\"disabled\":true,\"type\":\"button\"}).html(((streetInfo.myStreet)[i]).districtNm);\n");
      out.write("           \t\t\t\t\t$sector2.append($sdistrict);\n");
      out.write("           \t\t\t\t\t$divPlus31.append($sector1).append($sector2);\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t$divPlus3.append($divPlus31);\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 3_2\n");
      out.write("\t\t\t\t\t\t\tvar $divPlus32 = $(\"<div class='row'>\"); \n");
      out.write("           \t\t\t\t\tvar $sector3 = $(\"<div class='col-md-12'>\");\n");
      out.write("           \t\t\t\t\tvar $sinfo = $(\"<textarea class='form-control'>\").prop({\"rows\":\"2\",\"cols\":\"65\",\"readonly\":true})\n");
      out.write("           \t\t\t\t\t\t\t\t.css(\"resize\",\"none\").html(((streetInfo.myStreet)[i]).streetIntro);\n");
      out.write("           \t\t\t\t\t$sector3.append($sinfo);\n");
      out.write("           \t\t\t\t\t$divPlus32.append($sector3)\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t$divPlus3.append($divPlus32);\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 3_3\n");
      out.write("           \t\t\t\t\tvar $divPlus33 = $(\"<div class='row'>\");\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 해당 골목이 키워드를 가지고 있는지 파악\n");
      out.write("           \t\t\t\t\tvar count = 0;\n");
      out.write("           \t\t\t\t\tfor(var g=0;g<Object.keys(streetInfo.myStreetKeyword).length;g++){\n");
      out.write("           \t\t\t\t\t\tif( (streetInfo.myStreetKeyword)[g].streetNo == streetNo ) {\n");
      out.write("           \t\t\t\t\t\t\tcount++;\n");
      out.write("           \t\t\t\t\t\t} \n");
      out.write("           \t\t\t\t\t}\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 키워드가 존재하는 경우\n");
      out.write("           \t\t\t\t\tif(count > 0) { \n");
      out.write("           \t\t\t\t\t\tfor(var g=0;g<Object.keys(streetInfo.myStreetKeyword).length;g++){\n");
      out.write("               \t\t\t\t\t\tif( (streetInfo.myStreetKeyword)[g].streetNo == streetNo ) {\n");
      out.write("               \t\t\t\t\t\t\tvar $divPlus7 = $(\"<div class='col-md-12 golmokKeywordBox mt-1 mb-1'>\").css(\"background-color\",\"#36be81\");\n");
      out.write("               \t\t\t\t\t\t\tvar $inputPlus2 = $(\"<input class='form-control-plaintext nanum'>\").prop({\"type\":\"text\",\"readonly\":true})\n");
      out.write("       \t\t\t\t\t\t\t\t\t.css(\"color\",\"white\").val((streetInfo.myStreetKeyword)[g].keywordContent);\n");
      out.write("       \t\t\t\t\t\t\t\t\t$divPlus7.append($inputPlus2);\n");
      out.write("       \t\t\t\t\t\t\t\t\t$divPlus33.append($divPlus7);       \t\t\t\t\t\t\t\t\t\n");
      out.write("               \t\t\t\t\t\t\t$divPlus3.append($divPlus33);\n");
      out.write("               \t\t\t\t\t\t} \n");
      out.write("               \t\t\t\t\t}\n");
      out.write("           \t\t\t\t\t} \n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 3_4\n");
      out.write("           \t\t\t\t\tvar $divPlus341 = $(\"<div class='row'>\");\n");
      out.write("           \t\t\t\t\tvar $sector4 = $(\"<div class='col-md-3'>\");\n");
      out.write("           \t\t\t\t\tvar $labelPlus = $(\"<label class='col-sm-3 col-form-label text-center nanum'>\")\n");
      out.write("           \t\t\t\t\t\t\t\t\t.css({\"font-weight\":\"bold\",\"font-size\":\"16px\"}).html(\"골목 총 인원\");\n");
      out.write("\t\t\t\t\t\t\tvar $inputPlus3 = $(\"<input class='form-control-plaintext nanum'>\").prop({\"type\":\"text\",\"readonly\":true})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css({\"font-weight\":\"bold\",\"font-size\":\"25px\"}).val(((streetInfo.myStreet)[i]).streetMaxMember);\n");
      out.write("\t\t\t\t\t\t\t$sector4.append($inputPlus3);\n");
      out.write("\t\t\t\t\t\t\t$divPlus341.append($labelPlus).append($sector4);\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\tvar $sector5 = $(\"<div class='col-md-3'>\");\n");
      out.write("\t\t\t\t\t\t\tvar $labelPlus2 = $(\"<label class='col-sm-3 col-form-label text-center nanum'>\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css({\"font-weight\":\"bold\",\"font-size\":\"20px\"}).html(\"골목대장\");\n");
      out.write("\t\t\t\t\t\t\tvar $inputPlus4 = $(\"<input class='form-control-plaintext nanum'>\").prop({\"type\":\"text\",\"readonly\":true})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.css({\"font-weight\":\"bold\",\"font-size\":\"25px\"}).val(((streetInfo.myStreet)[i]).memberNm);\n");
      out.write("\t\t\t\t\t\t\t$sector5.append($inputPlus4);\n");
      out.write("\t\t\t\t\t\t\t$divPlus341.append($labelPlus2).append($sector5);\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$divPlus3.append($divPlus341);\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 3_5\n");
      out.write("           \t\t\t\t\tvar $divPlus35 = $(\"<div class='row'>\");\n");
      out.write("           \t\t\t\t\tvar $sector6 = $(\"<div class='col-md-12'>\");\n");
      out.write("           \t\t\t\t\tvar $mstreetbtn = $(\"<button class='btn btn-primary btn-lg btn-block nanum'>\").prop(\"type\",\"button\")\n");
      out.write("           \t\t\t\t\t\t\t\t\t.css(\"font-weight\",\"bold\").html(\"골목 이동\");\n");
      out.write("           \t\t\t\t\t$sector6.append($mstreetbtn);\n");
      out.write("\t\t\t\t\t\t\t$divPlus35.append($sector6);\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$divPlus3.append($divPlus35);\n");
      out.write("\t\t\t           \t\t\t\t\t\n");
      out.write("           \t\t\t\t\t// 통합 구성\n");
      out.write("           \t\t\t\t\tif(document.getElementById(\"myStreetInfomation\").childElementCount < (Object.keys(streetInfo.myStreet).length)*2) {\n");
      out.write("           \t\t\t\t\t\tvar $divPlus10 = $(\"<div class='row'>\");\n");
      out.write("               \t\t\t\t\tvar $hrPlus = $(\"<hr>\");\n");
      out.write("               \t\t\t\t\t$divPlus10.append($divPlus1).append($divPlus2).append($divPlus3);\n");
      out.write("               \t\t\t\t\t$(\"#myStreetInfomation\").append($divPlus10).append($hrPlus);\n");
      out.write("           \t\t\t\t\t}\n");
      out.write("           \t\t\t\t\t\n");
      out.write("           \t\t\t\t}\n");
      out.write("       \t\t\t\t}\n");
      out.write("       \t\t\t\t\n");
      out.write("       \t\t\t},\n");
      out.write("       \t\t\terror : function(e){\n");
      out.write("           \t\t\tconsole.log(\"ajax 통신 실패\");\n");
      out.write("           \t\t\tconsole.log(e);\n");
      out.write("           \t\t}\n");
      out.write("       \t\t\t\n");
      out.write("       \t\t});\n");
      out.write("       \t\t\n");
      out.write("       \t});\n");
      out.write("\t\t\n");
      out.write("    </script>\n");
      out.write("       \n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/header.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/header.jsp(10,0) '${pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/common/header.jsp(10,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(33,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty msg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t<script>alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\")</script>\n");
          out.write("\t\t");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/common/header.jsp(35,2) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("msg");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(38,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("detailUrl");
      // /WEB-INF/views/common/header.jsp(38,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("square");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f0);
        }
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005furl_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005furl_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005furl_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005furl_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f0_reused = false;
    try {
      _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
      // /WEB-INF/views/common/header.jsp(39,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setName("currentPage");
      // /WEB-INF/views/common/header.jsp(39,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setValue("1");
      int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
      if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      _jspx_th_c_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
      // /WEB-INF/views/common/header.jsp(40,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty param.districtNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fparam_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f1_reused = false;
    try {
      _jspx_th_c_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/common/header.jsp(41,3) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setName("districtNo");
      // /WEB-INF/views/common/header.jsp(41,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.districtNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f1 = _jspx_th_c_005fparam_005f1.doStartTag();
      if (_jspx_th_c_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
      _jspx_th_c_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
      // /WEB-INF/views/common/header.jsp(43,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty param.streetSort}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fparam_005f2(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f2 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f2_reused = false;
    try {
      _jspx_th_c_005fparam_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/common/header.jsp(44,3) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f2.setName("streetSort");
      // /WEB-INF/views/common/header.jsp(44,3) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.streetSort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f2 = _jspx_th_c_005fparam_005f2.doStartTag();
      if (_jspx_th_c_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f2);
      _jspx_th_c_005fparam_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f2_reused);
    }
    return false;
  }
}
