----------게시글 타입 추가--------------------
INSERT INTO BOARD_TYPE VALUES (0, 'NONE'); 
INSERT INTO BOARD_TYPE VALUES (1, '게시글파일'); 
INSERT INTO BOARD_TYPE VALUES (2, '일정'); 
INSERT INTO BOARD_TYPE VALUES (3, '투표'); 
INSERT INTO BOARD_TYPE VALUES (4, 'N빵'); 
INSERT INTO BOARD_TYPE VALUES (5, '스케치'); 
INSERT INTO BOARD_TYPE VALUES (6, '지도'); 

UPDATE STREET SET
STREET_INTRO = 'WASSUP SEOUL 소개 테스트',
STREET_STATUS = 'Y',
STREET_MAX_MEMBER = 30
WHERE STREET_NO = 2;

INSERT INTO BOARD VALUES ( SEQ_BOARD.NEXTVAL , '게시글 테스트 중',  SYSDATE, 'Y', 0 , 2, 7, 0);
