/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-25 00:23:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.street.streetDetail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fileUpload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1582162448499L));
    _jspx_dependants.put("jar:file:/C:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- summerNote script -->\r\n");
      out.write("\r\n");
      out.write("<!-- include summernote css/js-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>summerModal</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("\turl('https://fonts.googleapis.com/css?family=Poor+Story&display=swap');\r\n");
      out.write("\r\n");
      out.write(".nanum {\r\n");
      out.write("\tfont-family: 'Poor Story', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (min-width: 768px) {\r\n");
      out.write("\t.modal:before {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tvertical-align: middle;\r\n");
      out.write("\t\tcontent: \" \";\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-dialog {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"summerModal\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"insert\" method=\"post\" id=\"summernoteForm\">\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"summernote\" name=\"boardContent\"></textarea>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary nanum\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger nanum uploadBtn\">작성</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t/* ===============3/23 미현 수정================ */\r\n");
      out.write("\t\t\r\n");
      out.write("\t    //섬머노트 셋팅 뀨\r\n");
      out.write("\t      $('#summernote').summernote({\r\n");
      out.write("\t\t        height: 300,                 // set editor height 에디터 높이\r\n");
      out.write("\t\t        minHeight: null,             // set minimum height of editor 최소 높이\r\n");
      out.write("\t\t        maxHeight: null,             // set maximum height of editor 최대 높이\r\n");
      out.write("\t\t        focus: true,\t\t\t\t// 에디터 로딩후 포커스를 맞출지 여부\r\n");
      out.write("\t\t        lang: \"ko-KR\",\t\t\t\t// 한글 설정\r\n");
      out.write("\t\t        fontNames : [ '맑은고딕', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],\r\n");
      out.write("\t\t        fontNamesIgnoreCheck : [ '맑은고딕' ],\r\n");
      out.write("\t\t\t\tcallbacks: {\r\n");
      out.write("\t\t\t\t\tonImageUpload: function(files, editor, welEditable) {\r\n");
      out.write("\t\t\t\t\t\tfor (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t\t\t\t\t\t\tsendFile(files[i], this);\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t       \t   }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("      \t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("   \r\n");
      out.write("     /**\r\n");
      out.write("\t* 이미지 파일 업로드\r\n");
      out.write("\t*/\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on(\"click\",\".uploadBtn\",function(){\r\n");
      out.write("\t\tconsole.log(\"summernoteForm\");\r\n");
      out.write("\t\t$(\"#summernoteForm\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("     \r\n");
      out.write("\t\tfunction sendFile(file, el) {\r\n");
      out.write("\t\t\tdata = new FormData();\r\n");
      out.write("\t\t\tdata.append(\"file\", file);\r\n");
      out.write("\t\t\tdata.append(\"boardWriter\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\")\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : \"fileUpload\",\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tenctype: 'multipart/form-data',\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(el).summernote('editor.insertImage', result);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  error : function(e){\r\n");
      out.write("\t\t\t\t\t  console.log(\"ajax 실패\");\r\n");
      out.write("\t\t\t\t\t  console.log(e);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* =============== 미현 끝================ */\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
