/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-24 12:58:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.street.streetDetail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class post_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1582207161766L));
    _jspx_dependants.put("jar:file:/D:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/timeline.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>타임라인 글작성 영역</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t #map {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      /* Optional: Makes the sample page fill the window. */\r\n");
      out.write("      html, body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("      }\r\n");
      out.write("      #floating-panel {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 180px;\r\n");
      out.write("        left: 25%;\r\n");
      out.write("        z-index: 5;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        border: 1px solid #999;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-family: 'Roboto','sans-serif';\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write(" </style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"postLayoutView \" style=\"padding: 0%;\">\r\n");
      out.write("\t\t\t\t<form action=\"insert\" method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\t\trole=\"form\" onsubmit=\"return validate();\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"writePost\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"postArea nanum\" id=\"writePostArea\" name=\"boardContent\" rows=\"3\" placeholder=\"새로운 게시글을 작성해보세요\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"postCountView\" style=\"border: 1px solid black; height: 45px;\">\r\n");
      out.write("\r\n");
      out.write("                <!-- 사진 첨부 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form class=\"form-signin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-toggle=\"modal\" data-target=\"#summerModal\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img class=\"writeOption\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/imageIcon.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"arrow_box\">사진</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 동영상 첨부 -->\r\n");
      out.write("                <div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("                  <form class=\"form-signin\">\r\n");
      out.write("                    <a href=\"#\" data-toggle=\"modal\" data-target=\"#summerModal\"> \r\n");
      out.write("                      <img class=\"writeOption\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/film.png\" alt=\"\">\r\n");
      out.write("                      <p class=\"arrow_box\">동영상</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 파일첨부 -->\r\n");
      out.write("                <div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("                  <form class=\"form-signin\">\r\n");
      out.write("                    <a href=\"#\" data-toggle=\"modal\" data-target=\"#summerModal\"> \r\n");
      out.write("                      <img class=\"writeOption\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/paperclip.png\" alt=\"\">\r\n");
      out.write("                      <p class=\"arrow_box\">파일첨부</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("                  <img class=\"writeOption voteOption\" data-toggle=\"modal\" data-target=\"#voteModal\"\r\n");
      out.write("                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/vote.png\">\r\n");
      out.write("                  <p class=\"arrow_box\">투표</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("                  <img class=\"writeOption\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pie-chart.png\">\r\n");
      out.write("                  <p class=\"arrow_box\">N빵</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("                  <img class=\"writeOption mapOption\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/map.png\"\r\n");
      out.write("                        data-toggle=\"modal\" data-target=\"#mapModal\">\r\n");
      out.write("                  <p class=\"arrow_box\">지도</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"writeOptionArea shake\" style=\"width: 7%\">\r\n");
      out.write("                  <img class=\"writeOption sketchOption\" data-toggle=\"modal\" data-target=\"#sketchModal\"\r\n");
      out.write("                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/sketch.png\">\r\n");
      out.write("                  <p class=\"arrow_box\">스케치</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                <div id=\"writePostBtn\" style=\"display: inline-block; width: 18%; margin-bottom: 0px; height: 100%; float: right;\">\r\n");
      out.write("                  <button type=\"submit\" class=\"btn nanum\" style=\"height: 40px; font-size: 18px; font-weight: bolder; position: relative; bottom: 1px; right: 7px; float: right;\">작성</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 지도 모달 -->\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"mapModal\" data-backdrop=\"static\"\r\n");
      out.write("\t\t\t\ttabindex=\"-1\" role=\"dialog\" aria-labelledby=\"writerModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\" role=\"document\" style=\"width: 700px; height:1000px\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- content start -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal_content\" style=\"padding: 3px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\" nanum\" id=\"writePostArea1\" rows=\"6\" placeholder=\"게시글내용을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 1px solid black; color: black; font-size: 17px; height: 280px; width:100%\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input type=\"text\" placeholder=\"주소검색 버튼 클릭\" style=\"width:80%;\" name=\"address1\" id=\"address1\" class=\"postcodify_address\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input type=\"button\" value=\"주소 검색\" id=\"postcodify_search_button\"><br> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div id=\"map\"style=\"width: 100%; height: 300px; margin-top: 10px; border:2px black solid;\"></div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"map_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div id=\"map\" style=\"width:100%;height:600px;position:relative;overflow:hidden;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <div id=\"menu_wrap\" class=\"bg_white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            <div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                <form onsubmit=\"searchPlaces(); return false;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t                   \t\t\t 키워드 : <input type=\"text\" value=\"이태원 맛집\" id=\"keyword\" size=\"15\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    <button type=\"submit\">검색하기</button> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                </form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <ul id=\"placesList\"></ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <div id=\"pagination\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" style=\"width: 14%; height: 25px; font-size: 17px; float: right; margin-top:10px\">작성</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal_layer\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t<!-- 투표 모달 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"voteModal\" data-backdrop=\"static\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\"-1\" role=\"dialog\" aria-labelledby=\"writerModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\" style=\"width: 30%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"modal-title nanum\" id=\"checkMemModalLabel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-weight: bold;\">투표 게시글 작성</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- content start -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\" nanum\" id=\"writePostArea\" rows=\"6\" placeholder=\"게시글내용을 입력하세요.\"\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  style=\"border: 1px solid black; color: black; font-size: 17px; height: 100px; padding-bottom: 20px; width:100%\"></textarea>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"voteTitle\" placeholder=\"투표 제목\" style=\"width:80%; margin-left: 10px; margin-bottom:10px;\"><br>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>1</label><input type=\"text\" id=\"voteOption1\" placeholder=\"항목 입력\" style=\"width:80%; margin-left: 5px\"><br>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>2</label><input type=\"text\" id=\"voteOption2\" placeholder=\"항목 입력\" style=\"width:80%; margin-left: 5px\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>3</label><input type=\"text\" id=\"voteOption3\" placeholder=\"항목 입력\" style=\"width:80%; margin-left: 5px\">\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" style=\"width: 110px; height: 30px; font-size: 16px; margin-left: 37%;\">+항목추가</button><br>\r\n");
      out.write("\t\r\n");
      out.write("\t    \t\t\t\t\t\t\t<label style=\"width: 130px;\" ><input type='checkbox' class='check1' style=\"margin-left: 20%;\" />무기명 투표</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label style=\"width: 130px;\" ><input type='checkbox' id=\"check2\" class='check2' style=\"margin-left: 20%; display: inline-block;\" />복수 선택 허용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  id=\"repeatVote\" style=\"width: 10%; margin: 0; display: inline-block; float:right; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"vote\" style=\"width: 90px;\">복수 선택 개수:</label>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"vote\" style=\"display: inline-block; \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"unlimit\">제한없음</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"two\">2개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"three\">3개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"four\">4개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"five\">5개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label style=\"width: 25%;\" ><input type='checkbox' id='check3' style=\"margin-left: 20%;\" />종료일 설정</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  id=\"repeatVote\" style=\"width: 30%; margin: 0; display: inline-block; float:right; visibility:hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"vote\" style=\"width: 90px;\">복수 선택 개수:</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"vote\" style=\"display: inline-block; \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"unlimit\">제한없음</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"two\">2개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"three\">3개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"four\">4개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"five\">5개</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  id=\"setEndDate\" style=\"width: 30%; display: inline-block; float:right; visibility:hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label style=\"width: 130px;\" >종료일 선택<input type='date' /><input type='time' /></label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"voteSubmitBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 15%; height: 30px; font-size: 17px; float: right; margin: 0px\">작성</button>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" it=\"voteSubmitBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; height: 30px; font-size: 17px; float: right; margin: 0px\">작성</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 스케치 모달 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"sketchModal\" data-backdrop=\"static\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\"-1\" role=\"dialog\" aria-labelledby=\"writerModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\" style=\"width: 50%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"modal-title nanum\" id=\"checkMemModalLabel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-weight: bold;\">스케치 게시글 작성</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- content start -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\" nanum\" id=\"writePostArea2\" rows=\"6\" placeholder=\"게시글내용을 입력하세요.\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"border: 1px solid black; color: black; font-size: 17px; height: 100px; width:100%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"jb_table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("                              <canvas id=\"canvas\" width=\"420\" height=\"485\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <span class=\"cell\" id=\"draw\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jb_table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/red.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('red')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/orange.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('orange')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/yellow.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('yellow')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/green.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('green')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/blue.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('blue')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/lightblue.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('lightblue')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/brown.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('brown')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/lightgreen.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('lightgreen')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pink.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('pink')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/purple.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('purple')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/gray.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('gray')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/lightgray.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('lightgray')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/white.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectColor('white')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row drawing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"cell\" id=\"draw\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pencil.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"drawColor\" onclick=\"selectTool('pencil')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 5px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea id=\"history\" cols=\"40\" rows=\"37\"style=\"display: none;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div> Title<input id=\"title\" size=\"15\" style=\"display: inline-block;\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"saveImage\" download=\"image.png\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<INPUT type=\"button\" value=\"Save\" onClick=\"saveImage()\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<INPUT type=\"button\" value=\"Clear\" onClick=\"initPage()\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" style=\"width: 10%; height: 25px; font-size: 17px; float: right; margin-top: 10px\">작성</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t \r\n");
      out.write("\t\t\t\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t// 투표 게시글작성\r\n");
      out.write("\t$(\"#voteSubmitBtn\").click(function() {\r\n");
      out.write("\t\tvar postContent = $(this).parent().find(\"textarea\").val();\r\n");
      out.write("\t\t//var divBox = $(this).parent(\".box111\");\r\n");
      out.write("\t\tvar voteOption1 = $(\"#voteOption1\").val();\r\n");
      out.write("\t\tvar voteOption2 = $(\"#voteOption2\").val();\r\n");
      out.write("\t\tvar voteOption3 = $(\"#voteOption3\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"writeComment\",\r\n");
      out.write("\t\t\tdata : {\"postNo\" : postNo, \"commentContent\" : commentContent },\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\treplyCount++;\r\n");
      out.write("\t\t\t\t\t$(this).parent().parent().parent().prev(\"div\" > \".commentCount\").text(\"댓글\"+replyCount);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"댓글 작성 성공\");\r\n");
      out.write("\t\t\t\t\t$(this).parent().prev(\"div\" > \".writeCommentArea\" ).text('');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(this).parent().prev(\"div\" > \".writeCommentArea\" ).text('');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t$(this).parent().prev().find(\"textarea\").val= \"\";\r\n");
      out.write("\t\t\t\tconsole.log(\"댓글 입력 후 내용:\"+commentContent);\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t refreshList()\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
