/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-24 12:34:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.street;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class streetMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1582207161766L));
    _jspx_dependants.put("jar:file:/D:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\" \r\n");
      out.write("\t\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script async defer src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyB3B2jMzpJSy5YG5-T11FaB4SCKPkjQ3Sc&callback=initMap\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.css\" type=\"text/css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/timeline.css\" type=\"text/css\">\r\n");
      out.write("<title>타임라인 메인 화면</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\t  .drawColor:hover{\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      #canvas {\r\n");
      out.write("        border: 1px solid black;\r\n");
      out.write("      }\r\n");
      out.write("      .jb_table {\r\n");
      out.write("        display: table;\r\n");
      out.write("      }\r\n");
      out.write("      .drawing {\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        display: table-row;\r\n");
      out.write("      }\r\n");
      out.write("      #draw {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("      }\r\n");
      out.write("      .drawColor{\r\n");
      out.write("          width:32px;\r\n");
      out.write("          height: 32px;\r\n");
      out.write("          margin-left: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      a:hover {\r\n");
      out.write("\t\t   color: #0d0d0d;\r\n");
      out.write("\t\t   text-decoration: none;\r\n");
      out.write("\t }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color : rgb(221, 233, 218);\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 골목 네비바 여백 -->\r\n");
      out.write("\t<div class=\"container-fluid\" style=\"margin-top: 57px;\">\r\n");
      out.write("\t\t<div class=\"row\"  style=\"padding: 0px; height:44px\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 고정된 헤더 -->\r\n");
      out.write("\t ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t<!-- 컨텐츠영역-->\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/streetSide.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- 사이드1 여백 -->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\" id=\"devideArea\"></div>\r\n");
      out.write("\t\t\t<!-- 사이드1 여백 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 타임라인-->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\" id=\"devideArea\" style=\"margin-top: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 타임라인-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 사이드2 여백 -->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\" id=\"devideArea\"></div>\r\n");
      out.write("\t\t\t<!-- 사이드2 여백 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 컨텐츠영역 종료 -->\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 새로고침\r\n");
      out.write("\t\t\tfunction refreshList() {\r\n");
      out.write("\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 글삭제\r\n");
      out.write("\t\t\t$(\".deletePost\").click(function() {\r\n");
      out.write("\t\t\t\tvar postNo = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\t//var divBox = $(this).parent(\".box111\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"deletePost\",\r\n");
      out.write("\t\t\t\t\tdata : {postNo : postNo},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\tsystem.out.println(\"게시글 삭제 성공\")\r\n");
      out.write("\t\t\t\t\t\t\t//divBox.remove();\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tsystem.out.println(\"게시글 삭제 실패\")\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\trefreshList()\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글작성\r\n");
      out.write("\t\t\t$(\".commentBtn\").click(function() {\r\n");
      out.write("\t\t\t\tvar postNo = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\t//var divBox = $(this).parent(\".box111\");\r\n");
      out.write("\t\t\t\tvar commentContent = $(this).parent().prev().find(\"textarea\").val();\r\n");
      out.write("\t\t\t\tvar replyCount = $(this).parent().parent().parent().prev(\"div\" > \".commentCount\").text().substring( 2 );\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(replyCount==\"\"){\r\n");
      out.write("\t\t\t\t\treplyCount=0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tconsole.log(\"replyCount:\"+replyCount);\r\n");
      out.write("\t\t\t\tconsole.log(\"댓글입력내용:\"+commentContent);\r\n");
      out.write("\t\t\t\tconsole.log(\"댓글 입력 게시글 번호 :\"+postNo);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"writeComment\",\r\n");
      out.write("\t\t\t\t\tdata : {\"postNo\" : postNo, \"commentContent\" : commentContent },\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\treplyCount++;\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().parent().parent().prev(\"div\" > \".commentCount\").text(\"댓글\"+replyCount);\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"댓글 작성 성공\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().prev(\"div\" > \".writeCommentArea\" ).text('');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().prev(\"div\" > \".writeCommentArea\" ).text('');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\t$(this).parent().prev().find(\"textarea\").val= \"\";\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"댓글 입력 후 내용:\"+commentContent);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t refreshList()\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 대댓글작성\r\n");
      out.write("\t\t\t$(\".reCommentBtn\").click(function() {\r\n");
      out.write("\t\t\t\tvar replyNo = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tvar boardNo = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\tvar commentContent = $(this).parent().prev().find(\"textarea\").val();\r\n");
      out.write("\t\t\t\tvar reReplyCount = $(this).parent().parent().parent().prev(\"div\" > \".reCommentCount\").text().substring( 2 );\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(reReplyCount==\"\"){\r\n");
      out.write("\t\t\t\t\treReplyCount=0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tconsole.log(\"reReplyCount:\"+reReplyCount);\r\n");
      out.write("\t\t\t\tconsole.log(\"댓글입력내용:\"+commentContent);\r\n");
      out.write("\t\t\t\tconsole.log(\"대댓글 달린 댓글 번호 :\"+replyNo);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"writeReComment\",\r\n");
      out.write("\t\t\t\t\tdata : {\"replyNo\" : replyNo, \"commentContent\" : commentContent, \"boardNo\" : boardNo },\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\treReplyCount++;\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().parent().parent().prev(\"div\" > \".commentCount\").text(\"댓글\"+replyCount);\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"대댓글 작성 성공\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().prev(\"div\" > \".writeCommentArea\" ).text('');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().prev(\"div\" > \".writeCommentArea\" ).text('');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\t$(this).parent().prev().find(\"textarea\").val= \"\";\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"댓글 입력 후 내용:\"+commentContent);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t refreshList()\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 글수정\r\n");
      out.write("\t\t\t/* $(\".updatePost\").click(function() {\r\n");
      out.write("\t\t\t\tvar postNo = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\t//var divBox = $(this).parent(\".box111\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"updatePost\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tpostNo : postNo\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\tsystem.out.println(\"게시글 삭제 성공\")\r\n");
      out.write("\t\t\t\t\t\t\t//divBox.remove();\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tsystem.out.println(\"게시글 삭제 실패\")\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\trefreshList()\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 게시글 좋아요 클릭시 버튼 이미지 변경, 좋아요 기록\r\n");
      out.write("\t\t\t$(\".likeBtn\").click(function() {\r\n");
      out.write("\t\t\t\tvar postNo = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tvar img = $(this).attr(\"src\");\r\n");
      out.write("\t\t\t\tvar likeCount = $(this).parent().next(\"p\").text()\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (img == \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like.png\") {\r\n");
      out.write("\t\t\t\t\tlikeCount++;\r\n");
      out.write("\t\t\t\t\t$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like2.png');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tlikeCount--;\r\n");
      out.write("\t\t\t\t\t$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like.png');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ( likeCount==0){\r\n");
      out.write("\t\t\t\t\tlikeCount=\"\"\r\n");
      out.write("\t\t\t\t\t$(this).parent().next(\"p\").text(likeCount);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(this).parent().next(\"p\").text(likeCount);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"likeFunction\",\r\n");
      out.write("\t\t\t\t\tdata : {\"postNo\" : postNo},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"좋아요 등록 성공\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"좋아요 해제 성공\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 좋아요 클릭시 버튼 이미지 변경, 좋아요 기록\r\n");
      out.write("\t\t\t$(\".likeBtn2\").click(function() {\r\n");
      out.write("\t\t\t\tvar replyNo = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tvar boardNo = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\tvar img = $(this).attr(\"src\");\r\n");
      out.write("\t\t\t\tvar likeCount = $(this).parent().next(\"p\").text()\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (img == \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like.png\") {\r\n");
      out.write("\t\t\t\t\tlikeCount++;\r\n");
      out.write("\t\t\t\t\t$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like2.png');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tlikeCount--;\r\n");
      out.write("\t\t\t\t\t$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like.png');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ( likeCount==0){\r\n");
      out.write("\t\t\t\t\tlikeCount=\"\"\r\n");
      out.write("\t\t\t\t\t$(this).parent().next(\"p\").text(likeCount);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(this).parent().next(\"p\").text(likeCount);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"replyLikeFunction\",\r\n");
      out.write("\t\t\t\t\tdata : {replyNo : replyNo, boardNo : boardNo},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"좋아요 등록 성공\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"좋아요 해제 성공\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 대댓글 좋아요 클릭시 버튼 이미지 변경, 좋아요 기록\r\n");
      out.write("\t\t\t$(\".likeBtn3\").click(function() {\r\n");
      out.write("\t\t\t\tvar replyNo = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tvar boardNo = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\tvar img = $(this).attr(\"src\");\r\n");
      out.write("\t\t\t\tvar likeCount = $(this).parent().next(\"p\").text()\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (img == \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like.png\") {\r\n");
      out.write("\t\t\t\t\tlikeCount++;\r\n");
      out.write("\t\t\t\t\t$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like2.png');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tlikeCount--;\r\n");
      out.write("\t\t\t\t\t$(this).attr('src','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/like.png');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ( likeCount==0){\r\n");
      out.write("\t\t\t\t\tlikeCount=\"\"\r\n");
      out.write("\t\t\t\t\t$(this).parent().next(\"p\").text(likeCount);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(this).parent().next(\"p\").text(likeCount);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"reReplyLikeFunction\",\r\n");
      out.write("\t\t\t\t\tdata : {replyNo : replyNo, boardNo : boardNo},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"좋아요 등록 성공\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"좋아요 해제 성공\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 작성자 프로필 조회\r\n");
      out.write("\t\t\t$(\".writerImg, .writerNickName\" ).on(\"click\",function(){\r\n");
      out.write("\t\t\t\tvar memberNo = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"checkProfile\",\r\n");
      out.write("\t\t\t\t\tdata : { memberNo : memberNo },\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(mList){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 회원정보\r\n");
      out.write("\t\t\t\t\t\t$(\".checkMemProfileUrl\").prop(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/profileImage/\"+mList[0].memberProfileUrl);\r\n");
      out.write("\t\t\t\t\t\t$(\".checkMemNickName\").val(mList[0].memberNickname);\r\n");
      out.write("\t\t\t\t\t\t/* $(\"#memberEmail\").val(-); */\r\n");
      out.write("\t\t\t\t\t\t$(\".checkMemName\").val(mList[0].memberNm);\r\n");
      out.write("\t\t\t\t\t\t$(\".checkMemAge\").val(mList[0].memberAge);\r\n");
      out.write("\t\t\t\t\t\t$(\".checkMemPhone\").val(\"-\");\r\n");
      out.write("\t\t\t\t\t\tif(mList[0].memberGender == \"M\") {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".checkMemGender\").val(\"남성\");\t\r\n");
      out.write("\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".checkMemGender\").val(\"여성\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 회원정보 끝\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t    \t\t\t// 회원 관심사\r\n");
      out.write("\t\t\t\t\t\tvar $divPlus = $(\".checkMemProfileHobby\");\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t\t\t\t\tfor(var i=1;i<Object.keys(mList).length;i++){\r\n");
      out.write("\t\t\t\t\t\t\tif(i == 1) { // 제일 처음 관심사\r\n");
      out.write("\t\t\t\t\t\t\t\tvar $divPlus1 = $(\"<div class='col-sm-10'>\");\r\n");
      out.write("\t\t\t       \t\t\t\tvar $labelPlus = $(\"<label>\");\r\n");
      out.write("\t\t\t       \t\t\t\tvar $inputPlus = $(\"<input>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$labelPlus.addClass(\"col-sm-2 col-form-label text-center nanum\").css({\"font-weight\" : \"bold\",\"font-size\": \"16px\"}).html(\"관심분야\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$inputPlus.prop({\"type\":\"text\",\"readonly\":\"true\"}).css({\"color\" : \"blue\",\"font-size\": \"25px\"})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  .addClass(\"nanum form-control-plaintext\").val(\".\" + mList[1].hobbyName);\r\n");
      out.write("\t\t\t\t\t\t\t\t$divPlus1.append($inputPlus);\r\n");
      out.write("\t\t\t\t\t\t\t\tif(document.getElementByName(\"writerProfileHobby\").childElementCount < (Object.keys(mList).length-1)*2) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$divPlus.append($labelPlus);\r\n");
      out.write("\t\t   \t\t\t\t\t\t$divPlus.append($divPlus1);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t} else { // 그 다음 관심사\r\n");
      out.write("\t\t\t\t\t\t\t\tvar $divPlus1 = $(\"<div class='col-sm-10'>\");\r\n");
      out.write("\t\t\t       \t\t\t\tvar $labelPlus = $(\"<label>\");\r\n");
      out.write("\t\t\t       \t\t\t\tvar $inputPlus = $(\"<input>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$labelPlus.addClass(\"col-sm-2 col-form-label text-center nanum\").css({\"font-weight\" : \"bold\",\"font-size\": \"16px\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t$inputPlus.prop({\"type\":\"text\",\"readonly\":\"true\"}).css({\"color\" : \"blue\",\"font-size\": \"25px\"})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  .addClass(\"nanum form-control-plaintext\").val(\".\" + mList[i].hobbyName);\r\n");
      out.write("\t\t\t\t\t\t\t\t$divPlus1.append($inputPlus);\r\n");
      out.write("\t\t\t\t\t\t\t\tif(document.getElementByName(\"writerProfileHobby\").childElementCount < (Object.keys(mList).length-1)*2) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$divPlus.append($labelPlus);\r\n");
      out.write("\t\t   \t\t\t\t\t\t$divPlus.append($divPlus1);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 회원 관심사 끝\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e){\r\n");
      out.write("\t\t   \t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t   \t\t\tconsole.log(e);\r\n");
      out.write("\t\t   \t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t/* 회원 프로필 정보 조회용  */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  \t // 댓글 영역 숨기기\r\n");
      out.write("  \t\t$(\".commentArea\").click(function() {\r\n");
      out.write("  \t\t\t$(this).parent().next(\"div\").toggle(100);\r\n");
      out.write("  \t\t\t$('.writeCommentArea').focus();\r\n");
      out.write("  \t\t}); \r\n");
      out.write("\r\n");
      out.write("  \t\t// 대댓글 영역 숨기기\r\n");
      out.write("  \t\t$(\".doubleCommentArea\").click(function() {\r\n");
      out.write("  \t\t\t$(this).parent().parent().parent().next(\"div\").toggle(100);\r\n");
      out.write("  \t\t\t// $(\".inputCommentWrap\").toggle(500);\r\n");
      out.write("  \t\t\t$('.writeCommentArea2').focus();\r\n");
      out.write("  \t\t});\r\n");
      out.write("    \t\r\n");
      out.write("   \t\t//  게시글, 댓글 수정/삭제 메뉴창 보이기, 숨기기\r\n");
      out.write("   \t\t$(\".optionChevron>img\").click(function() {\r\n");
      out.write("   \t\t\t$(this).next(\"div\").toggleClass(\"hide\");\r\n");
      out.write("   \t\t});\r\n");
      out.write("\r\n");
      out.write("   \t\t$(\".likeNum\").click(function() {\r\n");
      out.write("   \t\t\t$(this).next(\"div\").toggleClass(\"hide\");\r\n");
      out.write("   \t\t});\r\n");
      out.write("\r\n");
      out.write("   \t\t// 게시글 작성 영역 높이 자동증가\r\n");
      out.write("   \t\t$('.writePost').on('keyup', 'textarea', function(e) {\r\n");
      out.write("   \t\t\t$(this).css('height', 'auto');\r\n");
      out.write("   \t\t\t$(this).height(this.scrollHeight);\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t\t$('.writePost').find('textarea').keyup();\r\n");
      out.write("\r\n");
      out.write("   \t\t// 댓글 작성 영역 높이 자동증가\r\n");
      out.write("   \t\t$('.inputCommentWrap').on('keyup', 'textarea', function(e) {\r\n");
      out.write("   \t\t\t$(this).css('height', 'auto');\r\n");
      out.write("   \t\t\t$(this).height(this.scrollHeight);\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t\t$('.inputCommentWrap').find('textarea').keyup();\r\n");
      out.write("\r\n");
      out.write("   \t\t// 댓글 출력 영역 높이 자동증가\r\n");
      out.write("   \t\t$('.commentContentWrap').on('keyup', 'textarea', function(e) {\r\n");
      out.write("   \t\t\t$(this).css('height', 'auto');\r\n");
      out.write("   \t\t\t$(this).height(this.scrollHeight);\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t\t$('.commentContentWrap').find('textarea').keyup();\r\n");
      out.write("\r\n");
      out.write("   \t\t// 게시글 출력 영역 높이 자동증가\r\n");
      out.write("   \t\t$('.postMainWrap').on('keyup', 'textarea', function(e) {\r\n");
      out.write("   \t\t\t$(this).css('height', 'auto');\r\n");
      out.write("   \t\t\t$(this).height(this.scrollHeight);\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t\t$('.postMainWrap').find('textarea').keyup();\r\n");
      out.write("\r\n");
      out.write("   \t\t// 게시물 없을때 게시글 작성 클릭시 커서 이동\r\n");
      out.write("   \t\t$(\".noPostSignArea\").click(function() {\r\n");
      out.write("   \t\t\t$('.postArea').focus();\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t// 지도 모달 창 열기 \r\n");
      out.write("\t\t$(\".mapOption\").click(function(){\r\n");
      out.write("\t\t\t$(this).parent().next(\"div\").attr(\"style\", \"display:block\");\r\n");
      out.write("\t    });\r\n");
      out.write("\t   \r\n");
      out.write("\t    $(\"#modal_close_btn\").click(function(){\r\n");
      out.write("\t\t\t$(this).parent().parent(\"div\").attr(\"style\", \"display:none\");\r\n");
      out.write("\t    });    \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t    // 투표 모달 중복투표 허용 옵션 보이기 \r\n");
      out.write("\t    $(\"#check2\").change(function(){\r\n");
      out.write("\t        if($(\"#check2\").is(\":checked\")){\r\n");
      out.write("\t        \t$(\"#repeatVote\").attr(\"style\", \"visibility:visible\");\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t        \t$(\"#repeatVote\").attr(\"style\", \"visibility:hidden\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t     \r\n");
      out.write(" \t\t// 투표 종료일 선택창  \r\n");
      out.write("\t    $(\"#check3\").change(function(){\r\n");
      out.write("\t        if($(\"#check3\").is(\":checked\")){\r\n");
      out.write("\t        \t$(\"#setEndDate\").attr(\"style\", \"visibility:visible\");\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t        \t$(\"#setEndDate\").attr(\"style\", \"visibility:hidden\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("    \t     \r\n");
      out.write("\t</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/friends.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/street/streetMain.jsp(54,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memGradeInSt.citizenStatus eq 'N'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/street/streetMain.jsp(58,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memGradeInSt.citizenStatus eq 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<!-- 고정된 골목 네비바  -->\r\n");
          out.write("\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/streetNav.jsp", out, false);
          out.write(" \r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/street/streetMain.jsp(79,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memGradeInSt.citizenStatus eq 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<!--회원 골목 가입 되어 있을때 -->\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<!-- 검색Bar-->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"row\" id=\"searchArea\" style=\"width: 99%; margin-left: 1px;\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/searchBar.jsp", out, false);
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<!-- 검색Bar -->\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\t\t\t<!-- 글작성 영역 -->\r\n");
          out.write("          <div class=\"container box111\" id=\"postArea\">\r\n");
          out.write("           ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/fileUpload.jsp", out, false);
          out.write(" \r\n");
          out.write("           ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/mapModal.jsp", out, false);
          out.write(" \r\n");
          out.write("            ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/post.jsp", out, false);
          out.write("\r\n");
          out.write("          </div>\r\n");
          out.write("          <!-- 글작성 영역 -->\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\t\t\t\t<!-- 중간여백 --><div class=\"row\" style=\"height: 20px; background-color: rgb(221, 233, 218);\"></div>\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\t\t\t\t<!-- 게시글영역-->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"postWrapView\">\r\n");
          out.write("\t\t\t\t\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../street/streetDetail/timeLine.jsp", out, false);
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<!-- 게시글영역 끝-->\r\n");
          out.write("\t\t\t\t\t<!--회원 골목 가입 되어 있을때 -->\t\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t<!-- 회원 골목 가입 안되어 있을때-->\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"container box111\" id=\"postArea\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"postLayoutView\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tstyle=\"padding: 0%; height: 500px; border: solid black 1px\">\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"nanum \" style=\"font-size: 20px; text-align: center;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"height: 200px\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"noPostSignArea container\" style=\"width: 50%;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"noPostSign\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t멤버만 게시글을 볼 수 있습니다.  <br> 골목에 가입해 보세요!\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<!--회원 골목 가입 되어 있을때 -->\t\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
