/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-24 12:34:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1582207161766L));
    _jspx_dependants.put("/WEB-INF/views/street/streetDetail/fileUpload.jsp", Long.valueOf(1585048351067L));
    _jspx_dependants.put("jar:file:/D:/workspace/Git/WassupSeoul/WassupSeoul/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write(" \r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("    integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mihyun_01.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\">\r\n");
      out.write("\r\n");
      out.write("  <title>Wassup, Seoul</title>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("    integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("   @import url('https://fonts.googleapis.com/css?family=Poor+Story&display=swap');\r\n");
      out.write("\r\n");
      out.write(".modal {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("@media screen and (min-width: 768px) { \r\n");
      out.write("        .modal:before {\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                vertical-align: middle;\r\n");
      out.write("                content: \" \";\r\n");
      out.write("                height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".modal-dialog {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("\r\n");
      out.write("        max-width: 100%; \r\n");
      out.write("        width: auto; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"backgroundPicture\">\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/서울4.jpg\" class=\"mainPicture\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container2\">\r\n");
      out.write("      <span class=\"titletext\">Wassup, Seoul</span>\r\n");
      out.write("\r\n");
      out.write("      <form class=\"form-signin\" form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login\" name=\"login\">\r\n");
      out.write("        <img class=\"mb-4\" src=\"{{ site.baseurl }}/docs/{{ site.docs_version }}/assets/brand/bootstrap-solid.svg\" alt=\"\"\r\n");
      out.write("          width=\"72\" height=\"72\">\r\n");
      out.write("        <h1 class=\"h1 mb-3 font-weight-bold nanum\">우리랑 같이 놀래?</h1>\r\n");
      out.write("        <label for=\"inputEmail\" class=\"sr-only\">Email address</label>\r\n");
      out.write("        <input type=\"email\" id=\"inputEmail\" name=\"memberEmail\" class=\"form-control nanum\" placeholder=\"이메일을 입력하세요\" required autofocus>\r\n");
      out.write("        <label for=\"inputPassword\" class=\"sr-only\">Password</label>\r\n");
      out.write("        <input type=\"password\" id=\"inputPassword\" name=\"memberPwd\" class=\"form-control nanum\" placeholder=\"비밀번호를 입력하세요\" required>\r\n");
      out.write("        <div class=\"checkbox mb-3\">\r\n");
      out.write("          <br>\r\n");
      out.write("          <label>\r\n");
      out.write("            <input type=\"checkbox\" value=\"remember-me\"> Remember me\r\n");
      out.write("          </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"btn btn-lg btn-primary btn-block nanum\" type=\"submit\">드루와</button>\r\n");
      out.write("        <br>\r\n");
      out.write("        <a href=\"\" style=\"font-size: 20px;\" data-toggle=\"modal\" data-target=\"#findEmailModal\">Find Email</a>\r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        <a href=\"#\" style=\"font-size: 20px;\" data-toggle=\"modal\" data-target=\"#findPwdModal\">Find Password</a>\r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/agreeForm\" style=\"font-size: 20px;\">Join us</a>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("      <!-- Eamil 찾기 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"findEmailModal\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h5 class=\"modal-title nanum\" style=\"font-size: 30px;\">Email 찾기</h5>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("            <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <span class=\"nanum\" style=\"font-size: 25px; color: tomato;\">Email</span>\r\n");
      out.write("          <span class=\"nanum\" style=\"font-size: 25px;\">을 잊으셨나요?</span>\r\n");
      out.write("          <br><br>\r\n");
      out.write("          <label for=\"\" class=\"nanum\">제 이름은</label>\r\n");
      out.write("          <input type=\"text\" id=\"memberNm1\" class=\"nanum\" size=\"10\"> \r\n");
      out.write("          <span class=\"nanum\">이고,</span>\r\n");
      out.write("          <label for=\"\" class=\"nanum\">휴대폰 번호는</label>\r\n");
      out.write("          <span class=\"nanum\" style=\"font-size: 15px; color: gray;\">(' - ' 포함)</span>&nbsp;&nbsp;\r\n");
      out.write("          <input type=\"text\" id=\"memberPhone1\" class=\"nanum\" size=\"20\">\r\n");
      out.write("          <span class=\"nanum\">이에요. &nbsp; </span> \r\n");
      out.write("          <br>\r\n");
      out.write("          <br>\r\n");
      out.write("          <div id=\"emailResultArea\">\r\n");
      out.write("         \t <div class=\"result-body\">\r\n");
      out.write("\t            <span class=\"nanum\" style=\"font-size: 25px; \">회원님의 Email은</span>\r\n");
      out.write("\t            <span class=\"nanum\" id=\"printEmail\" style=\"font-size: 25px; color: tomato;\" ></span>\r\n");
      out.write("\t            <span class=\"nanum\" style=\"font-size: 25px; \">입니다 ^3^</span>\r\n");
      out.write("           \t </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"emailResultFalseArea\">\r\n");
      out.write("         \t <div class=\"result-body\">\r\n");
      out.write("\t            <span class=\"nanum\" style=\"font-size: 25px; \">가입된 계정이 없습니다 !</span>\r\n");
      out.write("           \t </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-success nanum\" id=\"searchEmailBtn\">이메일 찾기</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary nanum\" data-dismiss=\"modal\" id=\"closeBtn1\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Pwd 찾기 -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"modal fade\" id=\"findPwdModal\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h5 class=\"modal-title nanum\" style=\"font-size: 30px;\">Password 찾기</h5>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("            <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("            <span class=\"nanum\" style=\"font-size: 25px; color: tomato;\">Password</span>\r\n");
      out.write("            <span class=\"nanum\" style=\"font-size: 25px;\">를 잊으셨나요?</span>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <label for=\"\" class=\"nanum\">제 이름은</label>\r\n");
      out.write("            <input type=\"text\" id=\"memberNm2\" class=\"nanum\" size=\"10\"> \r\n");
      out.write("            <span class=\"nanum\">이고,</span>\r\n");
      out.write("            <label for=\"\" class=\"nanum\">Email은</label>\r\n");
      out.write("            <input type=\"email\" id=\"memberEmail\" class=\"nanum\" size=\"20\"> \r\n");
      out.write("            <span class=\"nanum\">이에요. &nbsp; </span> \r\n");
      out.write("            <label for=\"\" class=\"nanum\">휴대폰 번호는</label>\r\n");
      out.write("            <span class=\"nanum\" style=\"font-size: 15px; color: gray;\">(' - ' 포함)</span>&nbsp;&nbsp;\r\n");
      out.write("            <input type=\"text\" id=\"memberPhone2\" class=\"nanum\" size=\"20\">\r\n");
      out.write("            <span class=\"nanum\">입니다. &nbsp; </span> \r\n");
      out.write("            <br><br>\r\n");
      out.write("            <div id=\"passwordResultArea\">\r\n");
      out.write("         \t <div class=\"result-body\">\r\n");
      out.write("\t            <span class=\"nanum\" style=\"font-size: 25px; \">회원님의 Email로 임시 비밀번호를 발송하였습니다 !</span>\r\n");
      out.write("           \t </div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          <div id=\"passwordResultFalseArea\">\r\n");
      out.write("         \t <div class=\"result-body\">\r\n");
      out.write("\t            <span class=\"nanum\" style=\"font-size: 25px; \">가입된 계정이 없습니다 !</span>\r\n");
      out.write("           \t </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-success nanum\" id=\"searchPasswordBtn\">비밀번호 찾기</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary nanum\" data-dismiss=\"modal\" id=\"closeBtn2\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- summerNote script -->\r\n");
      out.write("\r\n");
      out.write("<!-- include summernote css/js-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-bs4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>summerModal</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("\turl('https://fonts.googleapis.com/css?family=Poor+Story&display=swap');\r\n");
      out.write("\r\n");
      out.write(".nanum {\r\n");
      out.write("\tfont-family: 'Poor Story', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (min-width: 768px) {\r\n");
      out.write("\t.modal:before {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tvertical-align: middle;\r\n");
      out.write("\t\tcontent: \" \";\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-dialog {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"summerModal\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"insert\" method=\"post\" id=\"summernoteForm\">\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"summernote\" name=\"boardContent\"></textarea>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary nanum\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger nanum uploadBtn\">작성</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t/* ===============3/23 미현 수정================ */\r\n");
      out.write("\t\t\r\n");
      out.write("\t    //섬머노트 셋팅 뀨\r\n");
      out.write("\t      $('#summernote').summernote({\r\n");
      out.write("\t\t        height: 300,                 // set editor height 에디터 높이\r\n");
      out.write("\t\t        minHeight: null,             // set minimum height of editor 최소 높이\r\n");
      out.write("\t\t        maxHeight: null,             // set maximum height of editor 최대 높이\r\n");
      out.write("\t\t        focus: true,\t\t\t\t// 에디터 로딩후 포커스를 맞출지 여부\r\n");
      out.write("\t\t        lang: \"ko-KR\",\t\t\t\t// 한글 설정\r\n");
      out.write("\t\t        fontNames : [ '맑은고딕', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],\r\n");
      out.write("\t\t        fontNamesIgnoreCheck : [ '맑은고딕' ],\r\n");
      out.write("\t\t\t\tcallbacks: {\r\n");
      out.write("\t\t\t\t\tonImageUpload: function(files, editor, welEditable) {\r\n");
      out.write("\t\t\t\t\t\tfor (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t\t\t\t\t\t\tsendFile(files[i], this);\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t       \t   }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("      \t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("   \r\n");
      out.write("     /**\r\n");
      out.write("\t* 이미지 파일 업로드\r\n");
      out.write("\t*/\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on(\"click\",\".uploadBtn\",function(){\r\n");
      out.write("\t\tconsole.log(\"summernoteForm\");\r\n");
      out.write("\t\t$(\"#summernoteForm\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("     \r\n");
      out.write("\t\tfunction sendFile(file, el) {\r\n");
      out.write("\t\t\tdata = new FormData();\r\n");
      out.write("\t\t\tdata.append(\"file\", file);\r\n");
      out.write("\t\t\tdata.append(\"boardWriter\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\")\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : \"fileUpload\",\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tenctype: 'multipart/form-data',\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(el).summernote('editor.insertImage', result);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t  error : function(e){\r\n");
      out.write("\t\t\t\t\t  console.log(\"ajax 실패\");\r\n");
      out.write("\t\t\t\t\t  console.log(e);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* =============== 미현 끝================ */\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" <script>\r\n");
      out.write(" \r\n");
      out.write(" \t/* 이메일 찾기  */\r\n");
      out.write(" \t$(function(){\r\n");
      out.write("\t   $(\"#emailResultArea\").hide();\r\n");
      out.write("\t   $(\"#emailResultFalseArea\").hide();\r\n");
      out.write("\t   \r\n");
      out.write("\t   $(\"#searchEmailBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t   \r\n");
      out.write("\t \t\tif($(\"#memberNm1\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"이름을 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#memberNm1\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#memberPhone1\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"전화번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#memberPhone1\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t     var name = $(\"#memberNm1\").val();\r\n");
      out.write("\t     var phone = $(\"#memberPhone1\").val();\r\n");
      out.write("\t     \r\n");
      out.write("\t     console.log(name);\r\n");
      out.write("\t     console.log(phone);\r\n");
      out.write("\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t\t       url : \"member/findEmail\",\r\n");
      out.write("\t\t       data : {name, phone},\r\n");
      out.write("\t\t       success:function(result){\r\n");
      out.write("\t      \t\r\n");
      out.write("\t\t       \t if(result != 'null'){\r\n");
      out.write("\t\t\t         $(\"#printEmail\").text(result);\r\n");
      out.write("\t\t\t         $(\"#emailResultArea\").show();\r\n");
      out.write("\t\t\t         $(\"#emailResultFalseArea\").hide();\r\n");
      out.write("\t\t       \t }else{\r\n");
      out.write("\t\t       \t\t $(\"#resultFalseArea\").show();\r\n");
      out.write("\t\t       \t\t$(\"#emailResultFalseArea\").hide();\r\n");
      out.write("\t      \t\t }\r\n");
      out.write("\t\t     \t \r\n");
      out.write("\t     \t\t},\r\n");
      out.write("\t\t       \terror:function(){\r\n");
      out.write("\t\t       \tconsole.log(\"ajax통신 실패\");\r\n");
      out.write("\t     \t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t \t}); \r\n");
      out.write("\t      \r\n");
      out.write("\t   $(\".close\").on(\"click\",function(){\r\n");
      out.write("\t\t     $(\"#memberNm1\").val(\"\");\r\n");
      out.write("\t\t     $(\"#memberPhone1\").val(\"\");\r\n");
      out.write("\t\t     $(\"#emailResultArea\").hide();\r\n");
      out.write("\t\t     $(\"#emailResultFalseArea\").hide();\r\n");
      out.write("\t\t     \r\n");
      out.write("\t   });\r\n");
      out.write("\t   $(\"#closeBtn1\").on(\"click\",function(){\r\n");
      out.write("\t\t  \t $(\"#memberNm1\").val(\"\");\r\n");
      out.write("\t\t     $(\"#memberPhone1\").val(\"\");\r\n");
      out.write("\t   \t\t$(\"#emailResultArea\").hide();\r\n");
      out.write("\t     \t$(\"#emailResultFalseArea\").hide();\r\n");
      out.write("\t   });\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   /* 비밀번호 찾기  */\r\n");
      out.write("   $(function(){\r\n");
      out.write("   $(\"#passwordResultArea\").hide();\r\n");
      out.write("   $(\"#passwordResultFalseArea\").hide();\r\n");
      out.write("   \r\n");
      out.write("   $(\"#searchPasswordBtn\").on(\"click\",function(){\r\n");
      out.write("\t   \r\n");
      out.write(" \t\tif($(\"#memberNm2\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"이름을 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#memberNm2\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write(" \t\tif($(\"#memberEmail\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"이메일을 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#memberEmail\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write(" \t\t}\r\n");
      out.write("\t\tif($(\"#memberPhone2\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"전화번호를 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#memberPhone2\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("     var name = $(\"#memberNm2\").val();\r\n");
      out.write("     var email = $(\"#memberEmail\").val();\r\n");
      out.write("     var phone = $(\"#memberPhone2\").val();\r\n");
      out.write("     \r\n");
      out.write("     console.log(name);\r\n");
      out.write("     console.log(email);\r\n");
      out.write("     console.log(phone);\r\n");
      out.write("\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("    \t\t\r\n");
      out.write("\t       url : \"member/findPassword\",\r\n");
      out.write("\t       data : {name, email, phone},\r\n");
      out.write("\t       success:function(result){\r\n");
      out.write("      \t\r\n");
      out.write("\t       \t if(result != 'null'){\r\n");
      out.write("\t\t         $(\"#passwordResultArea\").show();\r\n");
      out.write("\t\t         $(\"#passwordResultFalseArea\").hide();\r\n");
      out.write("\t       \t }else{\r\n");
      out.write("\t       \t\t $(\"#passwordResultFalseArea\").show();\r\n");
      out.write("\t       \t\t$(\"#passwordResultArea\").hide();\r\n");
      out.write("      \t\t }\r\n");
      out.write("\t     \t \r\n");
      out.write("     \t\t},\r\n");
      out.write("\t       \terror:function(){\r\n");
      out.write("\t       \tconsole.log(\"ajax통신 실패\");\r\n");
      out.write("     \t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write(" \t}); \r\n");
      out.write("      \r\n");
      out.write("   $(\".close\").on(\"click\",function(){\r\n");
      out.write("\t     $(\"#memberNm2\").val(\"\");\r\n");
      out.write("\t     $(\"#memberEmail\").val(\"\");\r\n");
      out.write("\t     $(\"#memberPhone2\").val(\"\");\r\n");
      out.write("\t     $(\"#passwordResultArea\").hide();\r\n");
      out.write("\t     $(\"#passwordResultFalseArea\").hide();\r\n");
      out.write("\t     \r\n");
      out.write("   });\r\n");
      out.write("   $(\"#closeBtn2\").on(\"click\",function(){\r\n");
      out.write("\t  \t$(\"#memberNm2\").val(\"\");\t\r\n");
      out.write("\t  \t$(\"#memberEmail\").val(\"\");\r\n");
      out.write("\t    $(\"#memberPhone2\").val(\"\");\r\n");
      out.write("   \t\t$(\"#passwordResultArea\").hide();\r\n");
      out.write("     \t$(\"#passwordResultFalseArea\").hide();\r\n");
      out.write("   });\r\n");
      out.write(" });\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("    integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
